services:
  pg:
    image: postgres:17
    volumes: 
      - pg_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_PORT=5432
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=passkeeper_test
    ports:
      - ${POSTGRES_PORT:-5432}:5432

volumes:
  pg_data:
